---
abstract: 'DHL API client, non-blocking'
author:
  - 'Gianni Ceccarelli <gianni.ceccarelli@net-a-porter.com>'
build_requires:
  Carp: '0'
  Config::Any: '0'
  Data::Printer: '0'
  Data::Visitor::Callback: '0'
  File::Spec: '0'
  File::Temp: '0'
  HTTP::Request::Common: '0'
  HTTP::Response: '0'
  Moo::Role: '0'
  Scalar::Util: '0'
  StackTrace::Auto: '0'
  Test::Deep: '0'
  Test::More: '0'
  Test::Most: '0'
  Throwable: '0'
  Time::HiRes: '0'
  XML::Simple: '0'
  lib: '0'
  overload: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Async-Webservice-DHL
no_index:
  directory:
    - t/lib
recommends:
  IO::Async::Loop: '0'
  LWP::UserAgent: '0'
  Net::Async::HTTP: '0'
requires:
  DateTime: '0'
  DateTime::Format::ISO8601: '0'
  Encode: '0'
  Error::TypeTiny: '0'
  File::ShareDir::ProjectDistDir: '0'
  Future: '0'
  HTTP::Request: '0'
  List::AllUtils: '0'
  Moo: '0'
  Net::Async::Webservice::Common: '0'
  Try::Tiny: '0'
  Type::Library: '0'
  Type::Params: '0'
  Type::Utils: '0'
  Types::DateTime: '0'
  Types::Standard: '0'
  Types::URI: '0'
  XML::Compile::Cache: '0'
  XML::LibXML: '0'
  namespace::autoclean: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  repository: git://github.com/NET-A-PORTER/Net-Async-Webservice-DHL.git
version: 1.1.1
